version: 2

jobs:
  build:
    docker:
      - image: marlon365/mplab-xc32-2.10:sat-xc32-2.10-fw
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt-get -y install ca.certificate
      - run:
          name: Build
          command: |
            cd AXIOM_Remote_Prototype_V01.X 
            export MP_CC="/opt/microchip/xc32/v2.10/bin/xc32-gcc" 
            export MP_CC_DIR="/opt/microchip/xc32/v2.10/bin/"
            make -f nbproject/Makefile-default.mk SUBPROJECTS= .build-conf 
      - run:
          command: |
            mkdir /tmp/artefacts
            cp AXIOM_Remote_Prototype_V01.X/dist/default/production/* /tmp/artefacts
      - store_artifacts:
          path: /tmp/artefacts
