version: 2

jobs:
  build:
    docker:
      - image: marlon365/mplab-xc32-2.10:sat-xc32-2.10-fw
    steps:
      - checkout
      - run:
          name: Build
          command: |
            cd AXIOM_Remote_Prototype_V01.X 
            export MP_CC="/opt/microchip/xc32/v2.10/bin/xc32-gcc" 
            export MP_CC_DIR="/opt/microchip/xc32/v2.10/bin/"
            make -f nbproject/Makefile-default.mk SUBPROJECTS= .build-conf 
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./AXIOM_Remote_Prototype_V01.X/dist/default/production/*
      
