version: 2.1

#orbs:
#  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: bandit1983/xc32_ubuntu:latest
    steps:
      - checkout
      - run:
          name: Build
          command: |
            cd Firmware
            export MP_CC="/opt/microchip/xc32/v2.30/bin/xc32-gcc" 
            export MP_CC_DIR="/opt/microchip/xc32/v2.30/bin/"
            make -j8
      - run:
          command: |
            mkdir /tmp/artefacts
            cd Firmware/build
            mv AXIOM_Remote_Firmware.hex AXIOM_Remote_Firmware_${CIRCLE_BUILD_NUM}.hex
            md5sum AXIOM_Remote_Firmware_${CIRCLE_BUILD_NUM}.hex > AXIOM_Remote_Firmware_${CIRCLE_BUILD_NUM}.hex.md5
            cp *.hex *.md5 /tmp/artefacts
      - store_artifacts:
          path: /tmp/artefacts
  test:
    docker:
      - image: tangramor/cpptools:latest
    steps:
      - checkout
      - run:
          name: Build firmware tests
          command: |
            cd FirmwareTest
            mkdir build
            cd build
            cmake ..
            make -j8
            mkdir /tmp/test-results
            ./AXIOM_Remote_Firmware_Test -r junit > /tmp/test-results/AXIOM_Remote_Firmware_Test_results.xml
      - store_test_results:
          path: /tmp/test-results
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export CODECOV_TOKEN="42b5b27b-fb66-4e35-8d72-1277791370be"' >> $BASH_ENV
      - run:
          command: |
            bash <(curl -s https://codecov.io/bash) -f coverage_report/coverage_report.json
      #- codecov/upload:
      #    file: coverage_report/coverage_report.json
      #    flags: frontend

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
