version: 2

jobs:
  build:
    docker:
      - image: marlon365/mplab-xc32-2.10:sat-xc32-2.10-fw
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get -y update
            apt-get -y install git ca.certificate
      - checkout      
      - run:
          name: Build
          command: |
            cd AXIOM_Remote_Prototype_V01.X 
            export MP_CC="/opt/microchip/xc32/v2.10/bin/xc32-gcc" 
            export MP_CC_DIR="/opt/microchip/xc32/v2.10/bin/"
            make -f nbproject/Makefile-default.mk SUBPROJECTS= .build-conf 
      - run:
          command: |
            mkdir /tmp/artefacts
            cd AXIOM_Remote_Prototype_V01.X/dist/default/production/
            mv AXIOM_Remote_Prototype_V01.X.production.hex AXIOM_Remote_Prototype_V01.0.${CIRCLE_BUILD_NUM}.hex
            cp * /tmp/artefacts
      - store_artifacts:
          path: /tmp/artefacts
