version: 2

jobs:
  build:
    docker:
      - image: marlon365/mplab-xc32-2.10:sat-xc32-2.10-fw
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            export MP_CC="/opt/microchip/xc32/v2.10/bin/xc32-gcc" 
            export MP_CC_DIR="/opt/microchip/xc32/v2.10/bin/"
      - run:
          name: Build
          command: |
            cd AXIOM_Remote_Prototype_V01.X 
            make -f nbproject/Makefile-default.mk SUBPROJECTS= .build-conf 
